/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.macrometa.spark

import org.apache.spark.sql.functions.rand
import org.apache.spark.sql.{SaveMode, SparkSession}

object CollectionTest extends App {

    val apikey = "apikey "
    val federation = "support.eng.macrometa.io"
    val fabric = "_system"
    val sourceCollection = "collection_1"
    val batchSize = 10
    val query = s"FOR doc IN $sourceCollection RETURN doc"

    val spark = SparkSession.builder().master("local[*]").getOrCreate()

    val inputDF = spark.read
      .format("com.macrometa.spark.collection.MacrometaTableProvider")
      .option("federation", federation)
      .option("apiKey", apikey)
      .option("fabric", fabric)
      .option("collection", sourceCollection)
      .option("batchSize", batchSize)
      .option("query", query)
      .load()
    inputDF.show()

    val modifiedDF = inputDF.select("value").withColumnRenamed("value", "number").
      withColumn("randomNumber", rand())

    val targetCollection = "collection_2"
    modifiedDF.write.format("com.macrometa.spark.collection.MacrometaTableProvider")
      .option("federation", federation)
      .option("apiKey", apikey)
      .option("fabric", fabric)
      .option("collection", targetCollection)
      .option("primaryKey", "number")
      .mode(SaveMode.Append).save()

    spark.close()

}
