name: Macrometa Connector Databricks Release

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'Release from branch'
        required: true
      releaseVersion:
        description: 'Version to be released. (format - x.y.z)'
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Build and Publish JAR using Gradle
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          # Define input variables for version
          input_version: ${{ github.event.inputs.releaseVersion }}
        run: |
          # Extract the version and branch from the inputs
          NEW_VERSION=${{ env.input_version }}
          echo "New version: ${NEW_VERSION}"
          ./gradlew -Pversion=${NEW_VERSION} publish

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v${{ github.event.inputs.releaseVersion }}
          release_name: Release ${{ github.event.inputs.releaseVersion }}
          body: |
            Release version ${{ github.event.inputs.releaseVersion }}
          draft: false
          prerelease: false
